correct prompt() issues
Needed to change prompt.prompt() to just prompt() current raised an error.     
answers = prompt.prompt(questions, style=custom_style_3)
AttributeError: 'function' object has no attribute 'prompt'